### ISSUE TITLE
关于界面中无保存按钮？

### ISSUE THREAD

**Issue by xscan** [guobinnew/yuchang#3]
![image](https://user-images.githubusercontent.com/8383395/51423600-a7f46b80-1bfd-11e9-9203-1e75c027812d.png)

**Comment by guobinnew** [comment]
目前没有提供按钮，
在Vue页面中，
this.editor = yuchg.Scratch.init(dom)
调用this.editor.save()返回当前模型的JSON文本，然后可以自行解析转换为其他格式，
自定义的格式输出可以参考Markdown模块
